### ISSUE TITLE
Image and Font-Icon won't show up GitHub Page

### ISSUE THREAD

**Issue by keshibat** [anubhavsrivastava/gatsby-starter-prologue#1]
In dev-mode everything works as expected, but after I triggerd "npm run deploy" with no error message,
the image and font-awesome icon won't show up in Github page.

## Enviroment

Mac version:10.13.6
Node version: v10.15.3
Gatsby CLI version: 2.7.49
Gatsby version: 2.15.29

## How Reproduce

And run from your CLI:

```sh
gatsby new <site-name> https://github.com/anubhavsrivastava/gatsby-starter-prologue
```

```sh
cd gatsby-example-site
npm install
gatsby develop
```

```sh
git remote add <your-repository>
git push --set-upstream origin master
npm run deploy
```

http://localhost:8000/
![Imgur](https://i.imgur.com/49R0KEi.png) https://keshibat.github.io/test/
![Imgur](https://i.imgur.com/XHpJAzw.png)

Let me know if you need anything.
Thanks heaps

**Comment by anubhavsrivastava** [comment]
You need to change the path prefix in config.js.

`pathPrefix: '/gatsby-starter-prologue/',`

In your case, it is `/test/`

**Comment by keshibat** [comment]
That's exactly what I was missing.

Thanks heaps!
